language: cpp

sudo: false

addons:
  apt:
    packages:
      - ccache
      - gfortan #for silo
      - libhdf5-serial-dev #for silo
      - liblapack-dev
      - libblas-dev
      - libopenmpi-dev
      - openmpi-bin

env:
  matrix: 
    - COEVP_MPI=no 
    - COEVP_MPI=yes 

before_script:
  - export PATH="/usr/lib/ccache:$PATH"

script:
  - make -j2 COEVP_MPI=${COEVP_MPI}

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc

notifications:
  email:
    - tabasco-dev@lanl.gov  
